source:
  type: database
  params:
    uri: 'sslmode=require user=cache_warmer_prod password=Q1R$Rnf3ow host=10.11.0.65 port=5439 dbname=ta'
    driver: postgres
    url_column: 'uri'
    http_method_column: 'method'
    query: |-
      select uri, request_date, 'GET' as method
      FROM (
      select DISTINCT date_part(day, pi.from)         from_day,
      date_part(day, pi.to)           to_day,
      date_part(day, pi.request_date) date_event_day,
      *
      from (
      select DISTINCT TO_DATE(regexp_substr('http://localhost:8080' + api_id + '?' + query_params,
      'from=([0-9]{4}-[0-9]{2}-[0-9]{2})?', 1, 1, 'e'),
      'yyyy-MM-dd')                                                               as from,
      TO_DATE(regexp_substr('http://localhost:8080' + api_id + '?' + query_params,
      'to=([0-9]{4}-[0-9]{2}-[0-9]{2})?', 1, 1, 'e'),
      'yyyy-MM-dd')                                                               as to,
      'http://localhost:8080' + api_id + '?' + query_params                               as uri,
      date(event_timestamp)                                                               as request_date
      from destinations_api_logs
      where http_status_code = 200
      AND date(event_timestamp) >= date(getdate()) - INTERVAL '7 day' AND date(event_timestamp) < date(getdate())) pi
      where from_day = to_day
      AND to_day = date_event_day
      order by request_date desc) as p

transformations:
  - type: relative-time-shift
    params:
      relative_to: "$request_date"
      date_format: "2006-01-02"
      target_fields: [ "from", "to" ]

  - type: rewrite-host
    params:
      host: localhost:8080

  - type: write-header
    params:
      headers:
        requestid: cache-warmer

executor:
  type: http
  params:
    continue_on_error: true
    concurrency: 1
    timeout: 60s
